create database peliculas

use peliculas

create table generos
(
cod_genero numeric (3,0) not null identity (1,1)
,nom_genero varchar (30) not null
constraint PK_generos primary key (cod_genero)
)

create table actores
(
cod_actor numeric (9,0) not null identity (1,1)
,ape_actor varchar (30) not null
,nom_actor varchar (30) not null
constraint PK_actores primary key (cod_actor)
)

create table directores
(
cod_director numeric (9,0) not null identity (1,1)
,ape_director varchar (30) not null
,nom_director varchar (30) not null
,nacionalidad varchar (50) not null
constraint PK_directores primary key (cod_director)
)

create table peliculas
(
cod_pelicula numeric (10,0) not null identity (1,1)
,nom_pelicula varchar (30) not null
,cod_genero numeric (3,0) 
,clasificacion varchar (30)
,cod_director numeric (9,0)
,fec_estreno smalldatetime not null
constraint PK_peliculas primary key (cod_pelicula)
,constraint FK_peliculas_directores foreign key (cod_director) references directores (cod_director)
,constraint FK_peliculas_generos foreign key (cod_genero) references generos (cod_genero)
)
insert into generos (nom_genero)
values ('Acción')
insert into generos (nom_genero)
values ('Ciencia Ficción')
insert into generos (nom_genero)
values ('Animación')
insert into generos (nom_genero)
values ('Aventura')
insert into generos (nom_genero)
values ('Argentinas')
insert into generos (nom_genero)
values ('Comedia')
insert into generos (nom_genero)
values ('Terror')
insert into generos (nom_genero)
values ('Suspenso')
insert into generos (nom_genero)
values ('Drama')
insert into generos (nom_genero)
values ('Romántico')
insert into generos (nom_genero)
values ('Cortometraje')
insert into generos (nom_genero)
values ('Documental')
insert into generos (nom_genero)
values ('Infantiles')
insert into generos (nom_genero)
values ('Musical')
insert into generos (nom_genero)
values ('Deportes')
insert into generos (nom_genero)
values ('Thriller')
insert into generos (nom_genero)
values ('Biográfico')
insert into generos (nom_genero)
values ('Policial')
insert into generos (nom_genero)
values ('Guerra')
insert into generos (nom_genero)
values ('Religioso')
insert into generos (nom_genero)
values ('Catástrofe')


insert into actores(ape_actor, nom_actor)
values ('Willis', 'Bruce')
insert into actores(ape_actor, nom_actor)
values ('Rago', 'Pablo')
insert into actores(ape_actor, nom_actor)
values ('Freeman', 'Morgan')
insert into actores(ape_actor, nom_actor)
values ('Smith', 'Will')
insert into actores(ape_actor, nom_actor)
values ('Penn', 'Sean')
insert into actores(ape_actor, nom_actor)
values ('Walker', 'Paul')
insert into actores(ape_actor, nom_actor)
values ('Cranston', 'Bryan')
insert into actores(ape_actor, nom_actor)
values ('Sandler', 'Adam')
insert into actores(ape_actor, nom_actor)
values ('Paul', 'Aaron')
insert into actores(ape_actor, nom_actor)
values ('Darín', 'Ricardo') 
insert into actores(ape_actor, nom_actor)
values ('Francella', 'Guillermo')
insert into actores(ape_actor, nom_actor)
values ('Diesel', 'Vin')
insert into actores(ape_actor, nom_actor)
values ('Chan', 'Jackie')
insert into actores(ape_actor, nom_actor)
values ('Pitt', 'Brad')
insert into actores(ape_actor, nom_actor)
values ('Williams', 'Robin')
insert into actores(ape_actor, nom_actor)
values ('Jolie', 'Angelina')
insert into actores(ape_actor, nom_actor)
values ('Cruz', 'Penélope')
insert into actores(ape_actor, nom_actor)
values ('Moore', 'Demi')
insert into actores(ape_actor, nom_actor)
values ('Fox', 'Megan')
insert into actores(ape_actor, nom_actor)
values ('Aniston', 'Jennifer') 
insert into actores(ape_actor, nom_actor)
values ('Cox', 'Courtney')
insert into actores(ape_actor, nom_actor)
values ('Duff', 'Hilary')
insert into actores(ape_actor, nom_actor)
values ('Mara', 'Kate')
insert into actores(ape_actor, nom_actor)
values ('Knightley', 'Keira')
insert into actores(ape_actor, nom_actor)
values ('Simpson', 'Jessica')
insert into actores(ape_actor, nom_actor)
values ('Page', 'Ellen')
insert into actores(ape_actor, nom_actor)
values ('Watson', 'Ema')
insert into actores(ape_actor, nom_actor)
values ('González', 'Araceli')
insert into actores(ape_actor, nom_actor)
values ('Cid', 'Celeste')
insert into actores(ape_actor, nom_actor)
values ('Díaz', 'Julieta')
insert into actores(ape_actor, nom_actor)
values ('Tobal', 'Eugenia')
insert into actores(ape_actor, nom_actor)
values ('Schwarzenegger', 'Arnold')
insert into actores(ape_actor, nom_actor)
values ('Depp', 'Johnny')

insert into directores(ape_director, nom_director, nacionalidad)
values ('Campanella', 'Juan José', 'Argentina')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Spielberg', 'Steven', 'Estadounidense')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Tarantino', 'Quentin', 'Estadounidense')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Cameron', 'James', 'Canadiense')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Nolan', 'Christopher', 'Inglesa')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Burton', 'Tim', 'Estadounidense')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Hitchcock', 'Alfred', 'Estadounidense')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Eastwood', 'Clint', 'Estadounidense')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Polanski', 'Roman', 'Francesa')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Wenders', 'Wim', 'Alemana')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Mungiu', 'Cristian', 'Rumana')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Haneke', 'Michael', 'Austríaca')
insert into directores(ape_director, nom_director, nacionalidad)
values ('Verbinsky', 'Gore', 'Estadounidense')

insert into peliculas (nom_pelicula, cod_genero, clasificacion, cod_director, fec_estreno)
values ('El secreto de sus ojos', 1, '+13', 1, 2010-10-08)
insert into peliculas (nom_pelicula, cod_genero, clasificacion, cod_director, fec_estreno)
values ('Batman Returns', 2, '+13', 2, 2005-04-10)
insert into peliculas (nom_pelicula, cod_genero, clasificacion, cod_director, fec_estreno)
values ('Million dollar baby', 3, '+16', 8, 2004-05-27)
insert into peliculas (nom_pelicula, cod_genero, clasificacion, cod_director, fec_estreno)
values ('Terminator', 4, '+18', 4, 2000-02-15)
insert into peliculas (nom_pelicula, cod_genero, clasificacion, cod_director, fec_estreno)
values ('Interstellar', 5, 'ATP', 5, 2014-11-22)
insert into peliculas (nom_pelicula, cod_genero, clasificacion, cod_director, fec_estreno)
values ('Tiburón', 6, '+16', 2, 2003-10-28)
insert into peliculas (nom_pelicula, cod_genero, clasificacion, cod_director, fec_estreno)
values ('E.T. El Extraterrestre', 7, 'ATP', 2, 2000-08-31)
insert into peliculas (nom_pelicula, cod_genero, clasificacion, cod_director, fec_estreno)
values ('Frenesí', 8, '+16', 7, 2005-04-30)